name: splitpal
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.64.0
  google_fonts: ^5.0.0
  http: ^1.4.0
  flutter_stripe: ^10.0.0
  provider: ^6.0.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.9.0
  image_picker: ^1.0.4
  firebase_messaging: ^14.7.1
  firebase_storage: ^11.6.7
  math_expressions: ^2.2.0
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.7
  intl: ^0.20.2

  # Enables Flutter Driver extension for integration testing
  integration_test:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/splitpal_logo.png
